name: Test Build Workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Vue.js Web App
        run: |
          cd vuejs-webapp-sample
          npm install
          npm run build
          
      - name: Build Go Web App
        run: cd go-webapp-sample && go build .
