name: CI/CD Pipeline with Security Checks

on:
  push:
    branches: [ master ]
    paths:
      - 'vuejs-webapp-sample/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'vuejs-webapp-sample/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: vuejs-webapp-sample/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: vuejs-webapp-sample
    - name: Lint TypeScript
      run: npm run lint
      working-directory: vuejs-webapp-sample
    - name: Compile TypeScript
      run: npm run type-check
      working-directory: vuejs-webapp-sample
    - name: Check for Vulnerable Dependencies
      run: npm audit --production
      working-directory: vuejs-webapp-sample
    - name: Build
      run: npm run build
      working-directory: vuejs-webapp-sample