on:
  push:
    branches:
      - master
      - main
    paths:
      - 'vuejs-webapp-sample/**'
  pull_request:
    types:
      - edited
      - ready_for_review
    paths:
      - 'vuejs-webapp-sample/**'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: 'npm'
          cache-dependency-path: vuejs-webapp-sample/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: vuejs-webapp-sample

      - name: Lint TypeScript
        run: npm run lint
        working-directory: vuejs-webapp-sample
        continue-on-error: true

      - name: Compile TypeScript
        run: npm run type-check
        working-directory: vuejs-webapp-sample

      - name: Check for Vulnerable Dependencies
        run: npm audit
        working-directory: vuejs-webapp-sample
        continue-on-error: true
